/*
Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

*/

#include<stdio.h>
#include<bits/stdc++.h>
#include <algorithm>
using namespace std;

int main() {
	string s, t;
	cin >> s >> t;
	for (int i = 0; i < t.size(); i++) {
		t[i + 1] += s[i] - t[i];
	}
	cout << t[t.size() - 1];
}

/*
s=abc
  012
t=abcn
  0123

I iteration
t[1] = t[1] + s[0] - t[0]
	 = b + a - a = b

II iteration
t[2] = t[2] + s[1] - t[1]
     = c + b - b = c

III Iteration
t[3] = t[3] + s[2] - t[2]
     = n + c - c = n

Here comes the Output

-All letters persent in s is present in t.
-There is just one extra letter in t.
-Every character can be represented as an ASCII .
-ASCII value of the extra letter in t is derived as follows:
-Sum of all ASCII values of charcters in s -> sSum
-Sum of all ASCII values of charcters in t -> tSum
-Return the difference (tSum-sSum)

Example 1:
s = 'abc'
t = 'abcd'
sSum = 97+98+99 = 294
tSum = 97+98+99+100 = 394

Example 2:
s = 'abc'
t = 'dbac'
sSum = 97+98+99 = 294
tSum = 100+98+97+99 = 394

In both examples, d (100) is the extra letter, which is equivalent to (tSum - sSum).

*/

//Optimised Solution

class Solution {
public:
	char findTheDifference(string s, string t) {
		char v = 0;
		for (char c : s) v ^= c;
		for (char c : t) v ^= c;
		return v;
	}
};

/*
If we XOR one charecter twice it becomes zero . ( A^A==0) .
We took this idea. In the problem, we see one charecter added at any position after suffling our main string.

So, we can add two string (s,t). then iterate the whole string and find out the XOR of the element. The XOR of the whole string(s+t) is our answer. cause same elements returns 0 (A^A==0) . So, the element which appears once,that Remains in our XOR sum. Just return it.
*/

